version: "3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bank_account
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
   
volumes:
  db_data: {}
